enableGlobalCache: true

nodeLinker: node-modules

npmMinimalAgeGate: 4320

packageExtensions:
  '@typescript-eslint/eslint-plugin@*':
    dependencies:
      typescript: 6.0.3
  '@typescript-eslint/parser@*':
    dependencies:
      typescript: 6.0.3
  '@typescript-eslint/project-service@*':
    dependencies:
      typescript: 6.0.3
  '@typescript-eslint/type-utils@*':
    dependencies:
      typescript: 6.0.3
  '@typescript-eslint/typescript-estree@*':
    dependencies:
      typescript: 6.0.3
  '@typescript-eslint/utils@*':
    dependencies:
      typescript: 6.0.3
  ts-api-utils@*:
    dependencies:
      typescript: 6.0.3
  typescript-eslint@*:
    dependencies:
      typescript: 6.0.3
